version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - db:db
      - uags:uags
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  uags:
    build: ./uags
    ports:
      - "9980:8890"
    volumes:
      - ./config/uags:/config
    links:
      - db:db
